# Generated by Django 5.1.3 on 2024-11-25 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Delivery', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery',
            name='delivery_date',
        ),
    ]
