# Generated by Django 5.1.3 on 2024-11-30 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Delivery', '0003_addresses_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='deliver_otp',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='pickup_otp',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
