# Generated by Django 5.1.3 on 2024-11-30 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Delivery', '0004_delivery_deliver_otp_delivery_pickup_otp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='delivery',
            old_name='deliver_otp',
            new_name='dropoff_otp',
        ),
    ]
